package cn.pzhu.pserson.domain;

public class Finance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.id
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.count
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.info
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.time
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.id
     *
     * @return the value of finance.id
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.id
     *
     * @param id the value for finance.id
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.count
     *
     * @return the value of finance.count
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.count
     *
     * @param count the value for finance.count
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.info
     *
     * @return the value of finance.info
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.info
     *
     * @param info the value for finance.info
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.time
     *
     * @return the value of finance.time
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.time
     *
     * @param time the value for finance.time
     *
     * @mbg.generated Wed Oct 19 15:55:12 CST 2022
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}