package cn.pzhu.pserson.domain;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.id
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.name
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.count
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.input
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    private Integer input;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.output
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    private Integer output;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.id
     *
     * @return the value of inventory.id
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.id
     *
     * @param id the value for inventory.id
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.name
     *
     * @return the value of inventory.name
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.name
     *
     * @param name the value for inventory.name
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.count
     *
     * @return the value of inventory.count
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.count
     *
     * @param count the value for inventory.count
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.input
     *
     * @return the value of inventory.input
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public Integer getInput() {
        return input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.input
     *
     * @param input the value for inventory.input
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public void setInput(Integer input) {
        this.input = input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.output
     *
     * @return the value of inventory.output
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public Integer getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.output
     *
     * @param output the value for inventory.output
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    public void setOutput(Integer output) {
        this.output = output;
    }
}