package cn.pzhu.pserson.domain;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.id
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.name
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.count
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.in
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    private Integer in;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.out
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    private Integer out;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.id
     *
     * @return the value of inventory.id
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.id
     *
     * @param id the value for inventory.id
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.name
     *
     * @return the value of inventory.name
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.name
     *
     * @param name the value for inventory.name
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.count
     *
     * @return the value of inventory.count
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.count
     *
     * @param count the value for inventory.count
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.in
     *
     * @return the value of inventory.in
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public Integer getIn() {
        return in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.in
     *
     * @param in the value for inventory.in
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public void setIn(Integer in) {
        this.in = in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.out
     *
     * @return the value of inventory.out
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public Integer getOut() {
        return out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.out
     *
     * @param out the value for inventory.out
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    public void setOut(Integer out) {
        this.out = out;
    }
}