package cn.pzhu.pserson.domain;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.id
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.name
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.count
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.money
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.time
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.id
     *
     * @return the value of sale.id
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.id
     *
     * @param id the value for sale.id
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.name
     *
     * @return the value of sale.name
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.name
     *
     * @param name the value for sale.name
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.count
     *
     * @return the value of sale.count
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.count
     *
     * @param count the value for sale.count
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.money
     *
     * @return the value of sale.money
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.money
     *
     * @param money the value for sale.money
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.time
     *
     * @return the value of sale.time
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.time
     *
     * @param time the value for sale.time
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}