package cn.pzhu.pserson.dao.dao;

import cn.pzhu.pserson.domain.Inventory;
import cn.pzhu.pserson.domain.InventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    long countByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int deleteByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int insert(Inventory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int insertSelective(Inventory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    List<Inventory> selectByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    Inventory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int updateByExampleSelective(@Param("row") Inventory row, @Param("example") InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int updateByExample(@Param("row") Inventory row, @Param("example") InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int updateByPrimaryKeySelective(Inventory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 25 15:23:20 CST 2022
     */
    int updateByPrimaryKey(Inventory row);
}