package cn.pzhu.pserson.dao.dao;

import cn.pzhu.pserson.domain.Inventory;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    int insert(Inventory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    Inventory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    List<Inventory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Tue Oct 18 16:19:26 CST 2022
     */
    int updateByPrimaryKey(Inventory row);
}