package cn.pzhu.pserson.dao.dao;

import cn.pzhu.pserson.domain.Purchase;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    int insert(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    Purchase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    List<Purchase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    int updateByPrimaryKey(Purchase row);
}