package cn.pzhu.pserson.dao.dao;

import cn.pzhu.pserson.domain.Purchase;
import cn.pzhu.pserson.domain.PurchaseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    long countByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int deleteByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int insert(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int insertSelective(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    List<Purchase> selectByExampleWithBLOBs(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    List<Purchase> selectByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    Purchase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByExampleSelective(@Param("row") Purchase row, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") Purchase row, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByExample(@Param("row") Purchase row, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByPrimaryKeySelective(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByPrimaryKey(Purchase row);
}