package cn.pzhu.pserson.dao.dao;

import cn.pzhu.pserson.domain.Sale;
import cn.pzhu.pserson.domain.SaleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    long countByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int deleteByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int insert(Sale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int insertSelective(Sale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    List<Sale> selectByExampleWithBLOBs(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    List<Sale> selectByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    Sale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByExampleSelective(@Param("row") Sale row, @Param("example") SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") Sale row, @Param("example") SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByExample(@Param("row") Sale row, @Param("example") SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByPrimaryKeySelective(Sale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Sale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 20:27:37 CST 2022
     */
    int updateByPrimaryKey(Sale row);
}