package cn.pzhu.pserson.dao.dao;

import cn.pzhu.pserson.domain.Sale;
import java.util.List;

public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    int insert(Sale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    Sale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    List<Sale> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Tue Oct 18 13:14:14 CST 2022
     */
    int updateByPrimaryKey(Sale row);
}